// Word Builder word lists. Keep words in CAPITALS and pick emoji that clearly show the word.

const WORDS = {
  // 3-letter words — Little Learners (3–5)
  easy: [
    { word: "CAT", emoji: "🐱" },
    { word: "DOG", emoji: "🐶" },
    { word: "SUN", emoji: "☀️" },
    { word: "BUS", emoji: "🚌" },
    { word: "PIG", emoji: "🐷" },
    { word: "COW", emoji: "🐮" },
    { word: "HAT", emoji: "🎩" },
    { word: "BED", emoji: "🛏️" },
    { word: "CAR", emoji: "🚗" },
    { word: "EGG", emoji: "🥚" },
    { word: "BEE", emoji: "🐝" },
    { word: "FOX", emoji: "🦊" },
    { word: "OWL", emoji: "🦉" },
    { word: "ANT", emoji: "🐜" },
    { word: "BAT", emoji: "🦇" },
    { word: "KEY", emoji: "🔑" },
    { word: "MAP", emoji: "🗺️" },
    { word: "BOX", emoji: "📦" },
    { word: "PEN", emoji: "🖊️" },
    { word: "ICE", emoji: "🧊" },
  ],

  // 4–5 letter words — Young Explorers (6–8)
  medium: [
    { word: "FISH", emoji: "🐟" },
    { word: "CAKE", emoji: "🎂" },
    { word: "STAR", emoji: "⭐" },
    { word: "FROG", emoji: "🐸" },
    { word: "DUCK", emoji: "🦆" },
    { word: "BEAR", emoji: "🐻" },
    { word: "MOON", emoji: "🌙" },
    { word: "TREE", emoji: "🌳" },
    { word: "BOOK", emoji: "📖" },
    { word: "SHIP", emoji: "🚢" },
    { word: "LION", emoji: "🦁" },
    { word: "KITE", emoji: "🪁" },
    { word: "CORN", emoji: "🌽" },
    { word: "APPLE", emoji: "🍎" },
    { word: "HOUSE", emoji: "🏠" },
    { word: "TRAIN", emoji: "🚆" },
    { word: "HORSE", emoji: "🐴" },
    { word: "TIGER", emoji: "🐯" },
    { word: "PIZZA", emoji: "🍕" },
    { word: "ROBOT", emoji: "🤖" },
    { word: "SNAKE", emoji: "🐍" },
    { word: "ZEBRA", emoji: "🦓" },
    { word: "WHALE", emoji: "🐋" },
    { word: "MOUSE", emoji: "🐭" },
    { word: "CROWN", emoji: "👑" },
  ],
};
